/**
 * Represents the type of transaction to be performed.
 * Transaction value must match blockchain module & method!
 */
export enum ExtrinsicType {
  // Admins Pallet
  // AdminsAddAdmin = 'admins.addPalletAdmin',
  // AdminsRemoveAdmin = 'admins.removePalletAdmin',
  // AppAgents Pallet
  AppAgentsAddAdmin = 'appAgents.addAdmin',
  AppAgentsAddAdminToNamedAddress = 'appAgents.addAdminToNamedAddressDispatch',
  AppAgentsAllowAdminColdWallet = 'appAgents.allowAdminColdWalletDispatch',
  AppAgentsChangeHotWallet = 'appAgents.changeHotWallet',
  AppAgentsChangeOwnerCancel = 'appAgents.changeOwnerCancel',
  AppAgentsChangeOwnerComplete = 'appAgents.changeOwnerComplete',
  AppAgentsChangeOwnerInit = 'appAgents.changeOwnerInit',
  AppAgentsClearAdminDispatchFilter = 'appAgents.clearAdminDispatchFilter',
  AppAgentsClearAppAgentMetadata = 'appAgents.clearAppAgentMetadata',
  AppAgentsCompleteDestroyAppAgent = 'appAgents.completeDestroyAppAgent',
  AppAgentsCreateAppAgent = 'appAgents.createAppAgent',
  AppAgentsDisableAdminColdWalletDispatch = 'appAgents.disableAdminColdWalletDispatch',
  AppAgentsDisableHotWallet = 'appAgents.disableHotWallet',
  AppAgentsEnableHotWallet = 'appAgents.enableHotWallet',
  // AppAgentsForceCreateAppAgent = 'appAgents.forceCreateAppAgent',
  // AppAgentsForceInitiateAppAgentDestroy = 'appAgents.forceInitiateAppAgentDestroy',
  // AppAgentsForceInitiateAppAgentSuspension = 'appAgents.forceInitiateAppAgentSuspension',
  // AppAgentsForceInitiateAppAgentUnsuspension = 'appAgents.forceInitiateAppAgentUnsuspension',
  AppAgentsInitiateDestroyAppAgent = 'appAgents.initiateDestroyAppAgent',
  AppAgentsPauseAppAgent = 'appAgents.pauseAppAgent',
  AppAgentsProcessDestroy = 'appAgents.processDestroy',
  AppAgentsReactivateAppAgent = 'appAgents.reactivateAppAgent',
  AppAgentsRemoveAdmin = 'appAgents.removeAdmin',
  AppAgentsRemoveAdminFromNamedAddressDispatch = 'appAgents.removeAdminFromNamedAddressDispatch',
  AppAgentsSetAdminDispatchFilter = 'appAgents.setAdminDispatchFilter',
  AppAgentsSetAppAgentMetadata = 'appAgents.setAppAgentMetadata',
  AppAgentsUnpauseAppAgent = 'appAgents.unpauseAppAgent',
  // AppResources Pallet
  // AppResourcesSetActionPointsBalance = 'appResources.setActionPointsBalance',
  // AppResourcesSetClearingPointsBalance = 'appResources.setClearingPointsBalance',
  // AppSubscriptions Pallet
  // AppSubscriptionsCreateAppSubscriptionTier = 'appSubscriptions.createAppSubscriptionTier',
  // AppSubscriptionsObsoleteAppSubscriptionTier = 'appSubscriptions.obsoleteAppSubscriptionTier',
  AppSubscriptionsSetAppPayOnDemandMode = 'appSubscriptions.setAppPayOnDemandMode',
  AppSubscriptionsSetAppSubscriptionTier = 'appSubscriptions.setAppSubscriptionTier',
  // AppTransactions Pallet
  AppTransactionsSubmitClearingTransaction = 'appTransactions.submitClearingTransaction',
  // AppTransactionsForceSubmitClearingTransaction = 'appTransactions.forceSubmitClearingTransaction',
  // AppTransferChannels Pallet
  AppTransferChannelsEstablishTransferChannel = 'appTransferChannels.establishTransferChannel',
  AppTransferChannelsRemoveTransferChannel = 'appTransferChannels.removeTransferChannel',
  // AppTransferFilters Pallet
  AppTransferFiltersBlockAddressDeposits = 'appTransferFilters.blockAddressDeposits',
  AppTransferFiltersSetAppDepositPermissions = 'appTransferFilters.setAppDepositPermissions',
  AppTransferFiltersUnblockAddressDeposits = 'appTransferFilters.unblockAddressDeposits',
  // Assets Pallet
  AssetsCreate = 'assets.create',
  AssetsStartDestroy = 'assets.startDestroy',
  AssetsDestroyAccounts = 'assets.destroyAccounts',
  AssetsDestroyApprovals = 'assets.destroyApprovals',
  AssetsFinishDestroy = 'assets.finishDestroy',
  AssetsMint = 'assets.mint',
  AssetsBurn = 'assets.burn',
  AssetsTransfer = 'assets.transfer',
  AssetsTransferKeepAlive = 'assets.transferKeepAlive',
  AssetsForceTransfer = 'assets.forceTransfer',
  AssetsFreezeAccount = 'assets.freeze',
  AssetsThawAccount = 'assets.thaw',
  AssetsFreezeAsset = 'assets.freezeAsset',
  AssetsThawAsset = 'assets.thawAsset',
  AssetsTransferOwnership = 'assets.transferOwnership',
  AssetsSetMinBalance = 'assets.setMinBalance',
  AssetsSetMetadata = 'assets.setMetadata',
  // Balances Pallet
  BalancesTransfer = 'balances.transferAllowDeath',
  BalancesTransferKeepAlive = 'balances.transferKeepAlive',
  BalancesTransferAll = 'balances.transferAll',
  // Nfts Pallet
  NftsCreateCollection = 'nfts.create',
  NftsDestroyCollection = 'nfts.destroy',
  NftsTransferCollectionOwnership = 'nfts.transferOwnership',
  NftsAcceptCollectionOwnership = 'nfts.setAcceptOwnership',
  NftsSetCollectionMetadata = 'nfts.setCollectionMetadata',
  NftsClearCollectionMetadata = 'nfts.clearCollectionMetadata',
  NftsMintItem = 'nfts.mint',
  NftsBurnItem = 'nfts.burn',
  NftsTransferItem = 'nfts.transfer',
  NftsLockItemTransfer = 'nfts.lockItemTransfer',
  NftsUnlockItemTransfer = 'nfts.unlockItemTransfer',
  NftsSetItemMetadata = 'nfts.setMetadata',
  NftsClearItemMetadata = 'nfts.clearMetadata',
  // UserFreeTransactions Pallet
  // UserFreeTransactionsAppAgentBlacklistAddress = 'userFreeTransactions.appAgentBlacklistAddress',
  // UserFreeTransactionsAppAgentUnblacklistAddress = 'userFreeTransactions.appAgentUnblacklistAddress',
  // UserFreeTransactionsBlacklistAddress = 'userFreeTransactions.blacklistAddress',
  // UserFreeTransactionsClearAppAgentsFreeTransferInfos = 'userFreeTransactions.clearAppAgentsFreeTransferInfos',
  // UserFreeTransactionsClearAssetLastTransferBlocks = 'userFreeTransactions.clearAssetLastTransferBlocks',
  // UserFreeTransactionsClearNftLastTransferBlocks = 'userFreeTransactions.clearNftLastTransferBlocks',
  // UserFreeTransactionsClearUserFreeTransferInfos = 'userFreeTransactions.clearUserFreeTransferInfos',
  // UserFreeTransactionsSetFreeTransfersEnabled = 'userFreeTransactions.setFreeTransfersEnabled',
  // UserFreeTransactionsUnblacklistAddress = 'userFreeTransactions.unblacklistAddress',
  // UserTransactions Pallet
  // UserTransactionsSubmitTransferAllBalances = 'userTransactions.submitTransferAllBalances',
  // UserTransactionsSubmitTransferAssets = 'userTransactions.submitTransferAssets',
  // UserTransactionsSubmitTransferBalances = 'userTransactions.submitTransferBalances',
  // UserTransactionsSubmitTransferNfts = 'userTransactions.submitTransferNfts',
  // UserVerification Pallet
  // UserVerificationSetUserLevel = 'userVerification.setUserLevel',
}
